kind: PersistentVolume
apiVersion: v1
metadata:
  name: odoo-pv-volume
  labels:
    type: local
    app: odoo
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/odoo-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: odoo-pv-claim
  labels:
    app: odoo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
